### ISSUE TITLE
include or declare innerHTML as *.html file

### ISSUE THREAD

**Issue by zxcviqekjkasdfl9** [r22n/mbjspc#17]
IDE will not check contents of innerHTML = "&lt;div&gt;...";.
so split ts file and html file.

**Comment by r22n** [comment]
ideas;
- on compile time, and it is hard-coded. macro will be replaced or function returns hard-string.
- on runtime, and its soft-coded. include html-string through api (e.g. jsplugin resource)

**Comment by r22n** [comment]
programmer should replace included html file to inner-html even if I selected both conditions.
