### ISSUE TITLE
api reference jsdoc

### ISSUE THREAD

**Issue by r22n** [r22n/mbjspc#5]
help developers coding on vscode

**Comment by zxcviqekjkasdfl9** [comment]
how to read data in setData method by chart, table ? 

a | b | c | d
-- | -- | -- | --
A | a | x | 1
A | b | x | 2
A | c | x | 3
B | a | y | 4
B | b | y | 5
B | c | z | 6
C | a | z | 7
C | b | z | 8
D | a | z | 9

**Comment by r22n** [comment]
chart: 
"col/row definitions and sums" represent rows/cols specified by user at data source editor (colDefinitionList, rowDefinitionList, summaryDataList).

"cols/rows" reply fact data generated by each points for each definitions (colDataList, rowDataList) .

as a result, we will get all points of chart data;
```
// definitions of chart data picked by user at data source .
row defs = b c
col defs = a c
sums = d d1 // 2 counts

// all points aggregated original tables by user defined data source .
rows = a/x a/y a/z b/x b/y b/z c/x c/z // 8 counts
cols = A/x B/y B/z C/z D/z // 5 counts
points;
a/x A/x 1
b/x A/x 2
c/x A/x 3
...
c/z D/z NaN
( 5 x 8 x 2 = 80 counts)
```

table:
"item defs" represent column of table specified by user at data source (itemDefinitionList) .

"data" replys 2 dimensions array has raw table of original table can include user-specific custom calclated item (dataArray) .

```
items = a b c d
data;
A a x 1
A b x 2
```

**Comment by r22n** [comment]
and gantt:
type of data is Table.
"item defs" will be mapped with gantt data source;
```
start end ...row-defs elem key
```
start and end represents datetime number that is utc millis .
timezone apply offset into original data if user specified convert timezone at data source .

row-defs and elem are user-specific at data source .

key is auto generated item which is identify row .

as a result;
```
items = col1 col2 d c a key // start=col1 end=col2 row-defs=d,c elem=a
data;
643800332000 1643864400000 1 x A 1498111
643800332000 1643864400000 1 x A 1498112
...
```
